
#define OPENLDAP_PACKAGE "OpenLDAP"
#define OPENLDAP_VERSION "2.1.22"
#define LDAP_VENDOR_VERSION 20122
#define LDAP_VENDOR_VERSION_MAJOR 2
#define LDAP_VENDOR_VERSION_MINOR 1
#define LDAP_VENDOR_VERSION_PATCH 22
#define HAVE_MKVERSION 1
